# Generated by Django 3.2 on 2022-05-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='working_hours',
            field=models.CharField(max_length=200),
        ),
    ]
