# Generated by Django 3.2 on 2022-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='disc',
            field=models.TextField(default=' Cozy cafe '),
        ),
    ]
