# Generated by Django 3.2 on 2022-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cafe_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='recent_picture',
            field=models.ImageField(default=1, upload_to='media/images/recent_picture'),
            preserve_default=False,
        ),
    ]
