# Generated by Django 3.2 on 2022-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cafe_recent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='recent_picture',
            field=models.FileField(upload_to='media/images/recent_picture'),
        ),
    ]
