# Generated by Django 3.2 on 2022-06-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_review_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cafe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.cafe'),
        ),
    ]
