# Generated by Django 3.2 on 2022-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_review_cafe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='recent_picture_2',
            field=models.FileField(default=1, upload_to='media/images/recent_picture_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='recent_picture_3',
            field=models.FileField(default=1, upload_to='media/images/recent_picture_3'),
            preserve_default=False,
        ),
    ]
