# Generated by Django 3.2 on 2022-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220626_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='user_picture',
            field=models.ImageField(default='user.png', upload_to='media/images/profile'),
        ),
    ]
