# Generated by Django 3.2 on 2022-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cafe_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='review',
            name='user_picture',
            field=models.ImageField(default='user.png', upload_to='media/images/profile'),
        ),
    ]
